### ISSUE TITLE
这里有一些其他类型的graph，欢迎推荐新的文章和交流

### ISSUE THREAD

**Issue by ConanCui** [nnzhan/Awesome-Graph-Neural-Networks#1]
https://github.com/ConanCui/Research-Line

![image](https://user-images.githubusercontent.com/21979236/54983005-e7b54600-4fe6-11e9-9c87-733ad5922047.png)

**Comment by nnzhan** [comment]
We appreciate for your suggestions. We will add more papers according to your list.
